### ISSUE TITLE
Extra Comma at End?

### ISSUE THREAD

**Issue by larrypl** [ColumPaget/ColumsCut#6] opened 2018-01-18 16:29 UTC
I wouldn't have expected this comma at the end of the line when the range goes beyond the number of fields:
```
Helios:~ larry$ echo -e 'one one,one two,one three,one four,one five,one six,one seven,one eight\ntwo one,two two,two three,two four,two five,two six,two seven,two eight,two nine' | tee /dev/tty | ccut -d , -f 1-9
one one,one two,one three,one four,one five,one six,one seven,one eight
two one,two two,two three,two four,two five,two six,two seven,two eight,two nine
one one,one two,one three,one four,one five,one six,one seven,one eight,
two one,two two,two three,two four,two five,two six,two seven,two eight,two nine
```

**Comment by ColumPaget** [comment] 2018-01-18 19:15
hmm, that seems strange to me, because that's adding a comma that's not there in the input! But if that's how gnu cut does it, then I guess it makes sense to fit in with that.

**Comment by ColumPaget** [comment] 2018-01-18 19:16
Oh, hang on, I misunderstood you. You're saying there shouldn't be one after eight in the 3rd line?

**Comment by larrypl** [comment] 2018-01-18 23:21
Sorry - exactly right. I wouldn't expect there to be a comma after “one eight” on the third line.

**Comment by ColumPaget** [comment] 2018-01-28 16:38
I've looked into this one, and I've got to say I think it's a feature not a bug! You asked for 9 fields, and you got nine fields, though the last one is a blank field because there's no matching data in the input.  In fact this example:


echo 1,2,3,4 | ./ccut -d . -f 3,2,6,7

which outputs 

3,2,

arguably should output:

3,2,,

**Comment by larrypl** [comment] 2018-01-28 18:46
Good point - I like it! That normalizes the input into fixed numbers of fields.

**Comment by ColumPaget** [comment] 2018-01-29 09:56
Okay, now I just have to make it actually *do* that, as the current version doesn't.

**Comment by ColumPaget** [comment] 2018-02-11 18:10
Okay, got this to work for release v2.10. 

Pretty shocked to discover that gnu cut does this:

echo "1,2,3,4,5" | cut -d , -f 2,3,20,4,5
2,3,4,5

If you're using cut to extract fields into values (what else is it for?) you'll have the wrong things in the wrong boxes, if you see what I mean.

Anyways, gonna close this one now.

**Closed as completed by ColumPaget** 2018-02-11 18:10 UTC
